[package]
name = "ringdesign-mcpd"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "ringdesign-mcpd"
path = "src/main.rs"

[dependencies]
ringdesign-core.workspace = true
ringdesign-mcp.workspace = true
rmcp.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
tokio.workspace = true
hyper-util.workspace = true
