[package]
name = "ringdesign-gui"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "ringdesigner"
path = "src/main.rs"

[dependencies]
ringdesign-core.workspace = true
ringdesign-mcp.workspace = true
tokio.workspace = true
eframe.workspace = true
egui.workspace = true
egui_glow.workspace = true
egui-phosphor.workspace = true
egui_tiles.workspace = true
ringdesign-graph = { path = "../ringdesign-graph" }
ringdesign-graph-ui = { path = "../ringdesign-graph-ui" }
ringdesign-script = { path = "../ringdesign-script" }
rfd.workspace = true
nalgebra.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
