[package]
name = "ringdesign-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
nalgebra.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
log.workspace = true
rayon.workspace = true
image.workspace = true
parking_lot.workspace = true
