#!/usr/bin/env python3
"""Build a local, printable catalog from the actual CAD renders and reports."""
import base64
import html
import json
from pathlib import Path
import sys

root = Path(sys.argv[1])
rows = json.loads((root / "collection.json").read_text())
copy = {
    "aster": ("Aster", "Cushion seal", "Sand · one piece", "A quiet cushion face with broad, continuous shoulders. The seal stays blank for a satin finish or initials engraved after casting."),
    "tide": ("Tide", "Twelve reeds", "Sand · one piece", "Twelve generous reeds give the silver a changing rhythm of light. Straight ornament and softened edges keep the pattern practical to withdraw."),
    "lantern": ("Lantern", "Pierced gallery signet", "Investment · fit and join", "An octagonal seal floats over open side galleries. Head and shank are cast separately, fitted at the feet, and soldered or laser joined."),
    "aureole": ("Aureole", "Half-turn ribbon", "Investment · one piece", "A single continuous oval section turns through 180 degrees. The section shifts from a broad band to a narrow crest without an assembly seam."),
}
figures = []
svg = ['<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="1640" viewBox="0 0 1400 1640"><rect width="1400" height="1640" fill="#111111"/><text x="48" y="66" fill="#f0e9dc" font-family="serif" font-size="42">Four rings / workshop collection</text><text x="48" y="100" fill="#aaa49b" font-family="sans-serif" font-size="19">Editable geometry · 18.200 mm nominal bore · actual model renders</text>']
readme = ["# Workshop collection", "", "Four editable rings, all with an exact nominal 18.200 mm bore (approximately US 8.11). Open `index.html` for views and downloads. The renders show actual geometry; surface-finishing instructions describe the intended bench finish.", "", "| Ring | Route | Approximate metal weight | Evidence |", "|---|---|---:|---|"]
for index, row in enumerate(rows):
    slug = row["slug"]
    name, subtitle, route, description = copy[slug]
    status = "0 sampled obstructions · mold trial required" if row["process"] == "SandTwoPart" else "Blocked in all six tested sand pulls"
    wall = row["radial_wall_mm"] if row["radial_wall_mm"] is not None else row["local_wall"]["sampled_min_mm"]
    metal = "Sterling silver" if row["alloy"] == "Silver 925" else "14k gold"
    links = [("Editable project", "design.ring.json"), ("Pattern sheet", "pattern-package/molding-sheet.html"), ("Pattern 3MF", "pattern-package/pattern.3mf"), ("Release report", "pattern-package/report.json")]
    if slug in ("lantern", "aureole"):
        links.append(("CAD assembly / STEP", "cad-assembly/assembly-nominal.step"))
    if slug == "lantern":
        links = [("Editable assembly", "design.ring.json"), ("Assembly instructions", "cad-assembly/assembly-sheet.html"), ("Shank pattern", "component-1-pattern/pattern.3mf"), ("Head pattern", "component-8-pattern/pattern.3mf"), ("CAD assembly / STEP", "cad-assembly/assembly-nominal.step")]
    anchor = "".join(f'<a href="{slug}/{path}">{html.escape(label)}</a>' for label, path in links)
    buttons = "".join(f'<button type="button" data-view="{view}" aria-pressed="{str(view == "hero").lower()}">{label}</button>' for view, label in [("hero", "Three quarter"), ("side", "Side"), ("top", "Face")])
    figures.append(f'''<article data-ring="{slug}"><div class="photo"><img src="{slug}/hero.png" alt="{html.escape(name + ', ' + subtitle)}"></div><nav aria-label="{name} views">{buttons}</nav><p class="route">{route}</p><h2>{name} <span>{subtitle}</span></h2><p>{description}</p><dl><div><dt>Metal</dt><dd>{metal}</dd></div><div><dt>Weight estimate</dt><dd>{row['grams']:.2f} g</dd></div><div><dt>Screened section</dt><dd>{wall:.2f} mm</dd></div></dl><p class="finding">{status}</p><div class="links">{anchor}</div><details><summary>Manufacturing notes</summary><p>{html.escape(row['bench'])}</p></details></article>''')
    x = 48 + (index % 2) * 700
    y = 130 + (index // 2) * 730
    encoded = base64.b64encode((root / slug / "hero.png").read_bytes()).decode()
    svg.append(f'<image x="{x}" y="{y}" width="600" height="590" href="data:image/png;base64,{encoded}"/><text x="{x}" y="{y+608}" fill="#f0e9dc" font-family="serif" font-size="35">{name}</text><text x="{x}" y="{y+638}" fill="#c4baaa" font-family="sans-serif" font-size="21">{html.escape(subtitle)} / {row["grams"]:.2f} g</text><text x="{x}" y="{y+669}" fill="#aaa49b" font-family="sans-serif" font-size="18">{html.escape(route)}</text>')
    readme.append(f"| [{name}]({slug}/design.ring.json) | {route} | {row['grams']:.2f} g | {status}; screened section {wall:.2f} mm |")

page = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Four rings — workshop collection</title><style>
:root{color-scheme:dark;font:16px/1.65 system-ui,sans-serif;background:#111;color:#ddd8d0}*{box-sizing:border-box}body{max-width:1240px;margin:auto;padding:48px 28px}header{padding:20px 0 40px;border-bottom:1px solid #39352e}h1{font:clamp(38px,6vw,70px)/1.12 Georgia,serif;color:#f0e9dc;margin:12px 0 22px;letter-spacing:-.025em}header p{max-width:780px;color:#aaa49b}.overline{letter-spacing:.16em;font-size:12px;text-transform:uppercase;color:#d8bd87}.grid{display:grid;grid-template-columns:1fr 1fr;column-gap:46px;row-gap:42px}article{min-width:0;padding:20px 0 32px;border-bottom:1px solid #39352e}.photo{aspect-ratio:1;display:grid;place-items:center}img{display:block;width:100%;height:auto}h2{font:36px/1.3 Georgia,serif;margin:12px 0 18px;color:#f0e9dc}h2 span{font:16px/1.5 system-ui;display:block;color:#aaa49b;margin-top:3px}nav{display:flex;gap:8px;flex-wrap:wrap}button{background:transparent;border:0;border-bottom:2px solid transparent;padding:10px 8px;min-height:44px;color:#aaa49b;font:inherit;cursor:pointer}button[aria-pressed=true]{color:#ead4a7;border-color:#c9aa72}button:focus-visible,a:focus-visible,summary:focus-visible{outline:2px solid #d8bd87;outline-offset:4px}.route{font-size:13px;color:#cdb98f;letter-spacing:.04em;margin:24px 0 0}dl{display:flex;gap:24px;flex-wrap:wrap;border-top:1px solid #302e28;border-bottom:1px solid #302e28;padding:16px 0;margin:24px 0}dt{font-size:12px;color:#aaa49b}dd{margin:4px 0 0;font-variant-numeric:tabular-nums}.finding{font-size:14px;color:#bfc9b8}.links{display:flex;gap:12px 20px;flex-wrap:wrap}a{color:#e4c692;text-underline-offset:4px}details{margin-top:24px;color:#aaa49b}summary{cursor:pointer;min-height:44px}footer{padding:30px 0;color:#aaa49b}footer strong{color:#e6ded0}@media(max-width:720px){body{padding:24px 18px}.grid{grid-template-columns:1fr;gap:8px}header{padding-bottom:24px}}@media print{body{background:white;color:#222;padding:0}header,h1,h2,h2 span,.route,footer,footer strong,dt,.finding{color:#222}article{break-inside:avoid}nav{display:none}a{color:#222}.grid{gap:20px}.photo{aspect-ratio:1.3}img{max-height:320px;width:auto;max-width:100%}}
</style><header><div class="overline">RingDesigner · authored collection</div><h1>Four rings.<br>Two ways to make them.</h1><p>Two patterns designed around straight sand-mold withdrawal. Two designs free to twist and open into galleries. Every view below comes from its editable model; every ring has a measured manufacturing report.</p><p>18.200 mm nominal bore · millimeter source files · uncalibrated starting shrink allowances</p></header><main class="grid">'''+"".join(figures)+'''</main><footer><p><strong>What the checks establish.</strong> Aster and Tide have zero sampled obstructions in both mold halves at 0.100 and 0.075 mm ray pitch, no unresolved rays, and valid closed meshes. Their status remains “Review” because low-draft surfaces need a physical mold trial. The investment designs are blocked in all six tested axis-aligned sand orientations; this does not rule out specialized cores or other molding methods.</p><p><strong>Before manufacture.</strong> Calibrate shrink for the actual process and alloy. Wall values are radial samples for the sand rings and sampled local normals for the CAD parts; unsampled details still need inspection. Lantern’s weight sums its separate parts before fitting; its source assembly contains intentional contact stock. Use its two component patterns and review the joints at the bench. The collection is modeled and inspected, not physically cast.</p><p><a href="README.md">Technical notes</a> · <a href="verification.json">Source and finer-sampling checks</a> · <a href="independent-checks.json">Independent file checks</a> · <a href="contact-sheet.svg">Contact sheet</a> · <a href="contact-sheet.pdf">Printable PDF</a></p></footer><script>document.querySelectorAll('button[data-view]').forEach(b=>b.addEventListener('click',()=>{const a=b.closest('article');a.querySelector('img').src=a.dataset.ring+'/'+b.dataset.view+'.png';a.querySelectorAll('button').forEach(v=>v.setAttribute('aria-pressed',String(v===b)));}));</script></html>'''
(root / "index.html").write_text(page)
svg.append('<text x="48" y="1605" fill="#aaa49b" font-family="sans-serif" font-size="18">Sand designs: zero sampled obstructions; physical mold trials and alloy calibration remain required.</text></svg>')
(root / "contact-sheet.svg").write_text("\n".join(svg))
readme += ["", "The sand patterns were screened at 0.100 mm and 0.075 mm ray spacing, including both mold halves and the bore. Both remain **Review**, due to low-draft surface area; neither has a physical mold trial. Pattern compensation is applied once (1.9% starting shrink for sterling, 1.3% for 14k gold). These values require shop calibration.", "", "Lantern is a two-component assembly. Its nominal preview mesh is for visualization; the head feet contain fitting stock. Use `component-1-pattern/` and `component-8-pattern/`, fit the contact faces, and solder or laser join. The application’s analytic interference operation is unresolved for this combination; `independent-checks.json` records the separate OpenCascade intersection measurement. Its weight is the sum before removing fitting stock. The head uses an explicit placement transform; inspect and adjust both joints when resizing this assembly.", "", "For each ring: `design.ring.json` is the editable nominal source; `pattern-package/` contains the compensated STL/3MF, source, recipe, report, and manufacturing sheet. CAD designs also include STEP and component packages: Lantern preserves analytic surfaces; Aureole exports its faceted twisted surface (a large file). Lantern’s top-level pattern package selects the head. Never shrink-scale a pattern file again.", "", "Reproduce with `cargo run -p ringdesign-core --example workshop_collection -- NEW_DIRECTORY`, then `-- NEW_DIRECTORY --verify`. Run `tools/check_workshop_collection.py` using a Python environment containing `cadquery-ocp`, and `tools/catalog_workshop_collection.py` to rebuild this catalog. See the root `plan.md` for application validation and remaining physical/ML work.", ""]
(root / "README.md").write_text("\n".join(readme))
print(f"Catalog: {root / 'index.html'}")
