//! What a right-click on a seat's made solid or a struck stamp offers, a stamp's edits and its inspector.
use super::menu::{MenuAction, MenuItem};
use crate::icons::Icon;
use ringdesign_core::{RingDesign, setting::Stamp};

/// The view's switches a seat's rows tick.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Switches {
    /// Seats' solids and stamps resolved into the preview.
    pub live_cuts: bool,
    /// Every seat's cutters drawn over the ring.
    pub show_cutters: bool,
}

impl Default for Switches {
    fn default() -> Self {
        Self { live_cuts: true, show_cutters: false }
    }
}

/// One change to a struck stamp.
#[derive(Clone, Debug, PartialEq)]
pub enum StampEdit {
    /// Sunk into the band rather than raised on it.
    Cut(bool),
    /// Struck at the bench after the pour rather than cast.
    Bench(bool),
    Delete,
}

/// Why a driven design's stamps are not edited from the ring.
pub const DRIVEN: &str = "This design is generated by nodes: its stamps are the graph's to change";

/// The submenu a stamp's join and cut fold into.
pub const ATTACH: &str = "Attach";
/// The submenu a stamp's cast and bench fold into.
pub const STAGE: &str = "Stage";

/// The seat's layer, and the switches that show its cuts.
pub fn seat_items(design: &RingDesign, path: &[usize], switches: Switches) -> Vec<MenuItem> {
    let layer = super::selection::entry_at(design, path).map_or_else(|| "its layer".to_string(), |e| format!("layer \"{}\"", e.name));
    vec![
        MenuItem::new(format!("Select {layer}"), Icon::Layers, MenuAction::SeatLayer(path.to_vec()), "Choose the seat's layer in the Layers tool, where its stone and its made setting are edited"),
        MenuItem::new("Live cuts", Icon::Cutters, MenuAction::ToggleLiveCuts, "Resolve every made setting and stamp into the preview; off shows the cast stock alone and builds faster").ticked(switches.live_cuts),
        MenuItem::new("Show cutters", Icon::Cutters, MenuAction::ToggleCutters, "Draw every seat's cutters over the ring as a ghost").ticked(switches.show_cutters),
    ]
}

/// Edit, attach, stage and delete for stamp `index`, each refused on a driven design.
pub fn stamp_items(design: &RingDesign, index: usize) -> Vec<MenuItem> {
    let Some(stamp) = design.stamps.get(index) else { return Vec::new() };
    let plain = design.graph.is_none();
    let mut items = vec![MenuItem::new("Edit stamp…", Icon::Stamp, MenuAction::EditStamp(index), "Its name and where it stands, in an inspector").only_if(plain, DRIVEN)];
    for (cut, label, icon, hint) in [(false, "Join", Icon::CadUnion, "Raised on the band"), (true, "Cut", Icon::CadSubtract, "Sunk into the band")] {
        items.push(MenuItem::new(label, icon, MenuAction::Stamp { index, edit: StampEdit::Cut(cut) }, hint).under(ATTACH).ticked(stamp.cut == cut).only_if(plain, DRIVEN));
    }
    for (bench, label, icon, hint) in [(false, "Cast", Icon::Casting, "Cast in the pattern"), (true, "Bench", Icon::Workshop, "Struck at the bench after the pour; never in a pattern")] {
        items.push(MenuItem::new(label, icon, MenuAction::Stamp { index, edit: StampEdit::Bench(bench) }, hint).under(STAGE).ticked(stamp.bench == bench).only_if(plain, DRIVEN));
    }
    items.push(MenuItem::new("Delete stamp", Icon::Delete, MenuAction::Stamp { index, edit: StampEdit::Delete }, "Take the stamp off the ring").only_if(plain, DRIVEN));
    items
}

/// `edit` made to stamp `index` of `design`: the History label, or why not, with nothing changed.
pub fn edit(design: &mut RingDesign, index: usize, edit: &StampEdit) -> Result<String, String> {
    if design.graph.is_some() {
        return Err(DRIVEN.into());
    }
    let Some(stamp) = design.stamps.get_mut(index) else { return Err(format!("The design has no stamp {index}")) };
    let name = stamp.name.clone();
    Ok(match *edit {
        StampEdit::Cut(cut) => {
            stamp.cut = cut;
            format!("{} stamp \"{name}\"", if cut { "Cut" } else { "Join" })
        }
        StampEdit::Bench(bench) => {
            stamp.bench = bench;
            format!("{} stamp \"{name}\"", if bench { "Bench" } else { "Cast" })
        }
        StampEdit::Delete => {
            design.stamps.remove(index);
            format!("Delete stamp \"{name}\"")
        }
    })
}

/// Where stamp `index` of `before` stands in `after`, found by what it is: unchanged in place; else the stamp equal to it,
/// equals told apart by their order; else in place when the list kept its length and the stamp there its name or its
/// outline, which is an edit of it; else the one stamp of its name and outline. `None` when it is gone.
pub fn follow(before: &[Stamp], after: &[Stamp], index: usize) -> Option<usize> {
    let stamp = before.get(index)?;
    if after.get(index) == Some(stamp) {
        return Some(index);
    }
    let rank = before[..index].iter().filter(|s| *s == stamp).count();
    if let Some(i) = after.iter().enumerate().filter(|(_, s)| *s == stamp).map(|(i, _)| i).nth(rank) {
        return Some(i);
    }
    if before.len() == after.len() && (after[index].name == stamp.name || after[index].outline == stamp.outline) {
        return Some(index);
    }
    let mut alike = after.iter().enumerate().filter(|(_, s)| s.name == stamp.name && s.outline == stamp.outline).map(|(i, _)| i);
    match (alike.next(), alike.next()) {
        (Some(i), None) => Some(i),
        _ => None,
    }
}

/// What the stamp inspector did this frame.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Inspected {
    /// A value moved.
    pub changed: bool,
    /// An edit was let go: a drag ended or a field lost focus.
    pub settled: bool,
}

/// The stamp's name and where it stands, each field named for a reader.
pub fn inspector(ui: &mut egui::Ui, stamp: &mut Stamp) -> Inspected {
    let mut out = Inspected::default();
    let mut note = |r: egui::Response| {
        out.changed |= r.changed();
        out.settled |= r.drag_stopped() || r.lost_focus();
    };
    note(crate::controls::named(ui, "Name", "Stamp name", |ui| ui.text_edit_singleline(&mut stamp.name)));
    fn degrees(v: &mut f64, lo: f64, hi: f64) -> egui::DragValue<'_> {
        egui::DragValue::new(v).speed(0.5).range(lo..=hi).suffix("°").max_decimals(1)
    }
    fn mm(v: &mut f64, lo: f64, hi: f64) -> egui::DragValue<'_> {
        egui::DragValue::new(v).speed(0.01).range(lo..=hi).suffix(" mm").max_decimals(2)
    }
    note(crate::controls::named(ui, "Round the ring", "Stamp angle", |ui| ui.add(degrees(&mut stamp.theta_deg, -360.0, 720.0))));
    note(crate::controls::named(ui, "Across the band", "Stamp across", |ui| ui.add(mm(&mut stamp.v_mm, -50.0, 50.0))));
    note(crate::controls::named(ui, "Turn", "Stamp turn", |ui| ui.add(degrees(&mut stamp.rot_deg, -360.0, 360.0))));
    note(crate::controls::named(ui, "Stands", "Stamp height", |ui| ui.add(mm(&mut stamp.height_mm, 0.0, 5.0))));
    note(crate::controls::named(ui, "Sinks", "Stamp sink", |ui| ui.add(mm(&mut stamp.sink_mm, 0.0, 5.0))));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::viewport::menu::context_items_in;
    use crate::viewport::selection::Selection;
    use ringdesign_core::interaction::pick::{Entity, Pick};

    fn disc(name: &str) -> Stamp {
        let outline = (0..12).map(|i| {
            let t = std::f64::consts::TAU * f64::from(i) / 12.0;
            [t.cos(), t.sin()]
        });
        Stamp { name: name.into(), theta_deg: 270.0, v_mm: 0.0, rot_deg: 0.0, outline: outline.collect(), height_mm: 0.4, sink_mm: 0.3, draft_deg: 0.0, cut: false, bench: false, along_pull: false, tier: 0, top: Default::default() }
    }
    fn design() -> RingDesign {
        use ringdesign_core::field::{Layer, LayerEntry, SeatPadLayer};
        let mut d = RingDesign::default();
        d.layers.layers.push(LayerEntry::new("Centre", Layer::SeatPad(SeatPadLayer { solid: ringdesign_core::setting::SolidKind::Prong, ..Default::default() })));
        d.stamps = vec![disc("Moon"), disc("Star")];
        d
    }
    fn pick(entity: Entity) -> Pick {
        Pick { entity, world: [0.0, 10.0, 0.0], normal: [0.0, 1.0, 0.0], depth: 1.0, px: 0.0 }
    }
    fn rows(items: &[MenuItem]) -> Vec<(Option<&'static str>, String, bool, bool)> {
        items.iter().map(|i| (i.submenu, i.label.clone(), i.checked, i.enabled)).collect()
    }

    #[test]
    fn a_seat_offers_its_layer_and_the_switches_ticked_as_they_stand() {
        let d = design();
        let sel = Selection::default();
        let under = pick(Entity::Seat { path: vec![0], station: 0 });
        let items = context_items_in(&sel, Some(&under), &d, Switches { live_cuts: true, show_cutters: false });
        assert_eq!(crate::viewport::heading(&sel, Some(&under), &d).as_deref(), Some("Claw head on Centre"));
        assert_eq!(
            rows(&items[..3]),
            [(None, "Select layer \"Centre\"".to_string(), false, true), (None, "Live cuts".into(), true, true), (None, "Show cutters".into(), false, true)]
        );
        assert_eq!(items.iter().map(|i| i.action.clone()).take(3).collect::<Vec<_>>(), [MenuAction::SeatLayer(vec![0]), MenuAction::ToggleLiveCuts, MenuAction::ToggleCutters]);
        assert_eq!(items.len(), 3 + 4, "and the view's own four");
        let off = context_items_in(&sel, Some(&under), &d, Switches { live_cuts: false, show_cutters: true });
        assert_eq!((off[1].checked, off[2].checked), (false, true));
    }

    #[test]
    fn a_stamp_offers_edit_attach_stage_and_delete_with_its_own_ticked_and_none_on_a_driven_design() {
        let mut d = design();
        d.stamps[1].cut = true;
        let sel = Selection::default();
        let under = pick(Entity::Stamp { index: 1 });
        let items = context_items_in(&sel, Some(&under), &d, Switches::default());
        assert_eq!(crate::viewport::heading(&sel, Some(&under), &d).as_deref(), Some("Stamp \"Star\""));
        assert_eq!(
            rows(&items[..6]),
            [
                (None, "Edit stamp…".to_string(), false, true),
                (Some(ATTACH), "Join".into(), false, true),
                (Some(ATTACH), "Cut".into(), true, true),
                (Some(STAGE), "Cast".into(), true, true),
                (Some(STAGE), "Bench".into(), false, true),
                (None, "Delete stamp".into(), false, true),
            ]
        );
        assert_eq!(items[0].action, MenuAction::EditStamp(1));
        assert_eq!(items[5].action, MenuAction::Stamp { index: 1, edit: StampEdit::Delete });
        // The last one chosen stands in for an empty right-click.
        let mut chosen = Selection::default();
        chosen.click(Some(crate::viewport::Sel::Stamp(0)), crate::viewport::Mods::default());
        assert_eq!(context_items_in(&chosen, None, &d, Switches::default())[0].action, MenuAction::EditStamp(0));
        // A driven design's stamps are its graph's: every row says so and none acts.
        d.graph = Some(serde_json::json!({}));
        let driven = context_items_in(&sel, Some(&under), &d, Switches::default());
        assert!(driven[..6].iter().all(|i| !i.enabled && i.hint == DRIVEN));
    }

    #[test]
    fn a_stamp_is_followed_across_an_undo_by_what_it_is_and_let_go_when_gone() {
        let (moon, star, sun) = (disc("Moon"), disc("Star"), disc("Sun"));
        let all = vec![moon.clone(), star.clone(), sun.clone()];
        let less = vec![moon.clone(), sun.clone()];
        // A deletion undone: each stamp back to its own place.
        assert_eq!((follow(&less, &all, 0), follow(&less, &all, 1)), (Some(0), Some(2)));
        // Redone: the deleted one is gone and the one after it moves down.
        assert_eq!((follow(&all, &less, 1), follow(&all, &less, 2)), (None, Some(1)));
        // An edit of the stamp itself undone keeps its place, moved or renamed.
        let mut moved = all.clone();
        moved[1].theta_deg += 20.0;
        let mut renamed = all.clone();
        renamed[1].name = "Venus".into();
        assert_eq!((follow(&moved, &all, 1), follow(&renamed, &all, 1)), (Some(1), Some(1)));
        // Another design of the same length names none of them.
        let other: Vec<Stamp> = ["A", "B", "C"].iter().map(|n| Stamp { outline: disc(n).outline[..6].to_vec(), ..disc(n) }).collect();
        assert_eq!(follow(&all, &other, 1), None);
        // Twins keep their order, and a place past the end is nothing.
        let twins = vec![moon.clone(), moon.clone(), star.clone()];
        assert_eq!((follow(&twins, &twins, 1), follow(&twins, &[moon.clone(), star.clone()], 1)), (Some(1), Some(0)));
        assert_eq!(follow(&all, &all, 7), None);
        // The selection follows too: a stamp gone is let go, one moved is chosen where it went, and a hover on a stamp is let go.
        let mut s = Selection::default();
        s.click(Some(crate::viewport::Sel::Stamp(2)), crate::viewport::Mods::default());
        s.click(Some(crate::viewport::Sel::Stamp(1)), crate::viewport::Mods { shift: true, ..Default::default() });
        s.click(Some(crate::viewport::Sel::Part(4)), crate::viewport::Mods { shift: true, ..Default::default() });
        s.hovered(vec![pick(Entity::Stamp { index: 2 })]);
        s.under = Some(pick(Entity::Stamp { index: 1 }));
        s.follow_stamps(&all, &less);
        assert_eq!(s.items, [crate::viewport::Sel::Stamp(1), crate::viewport::Sel::Part(4)]);
        assert!(s.hover.is_none() && s.stack().is_empty() && s.under.is_none());
    }

    #[test]
    fn each_stamp_edit_changes_one_stamp_and_names_itself() {
        let mut d = design();
        assert_eq!(edit(&mut d, 0, &StampEdit::Cut(true)), Ok("Cut stamp \"Moon\"".into()));
        assert_eq!(edit(&mut d, 0, &StampEdit::Bench(true)), Ok("Bench stamp \"Moon\"".into()));
        assert!(d.stamps[0].cut && d.stamps[0].bench && !d.stamps[1].cut && !d.stamps[1].bench);
        assert_eq!(edit(&mut d, 0, &StampEdit::Cut(false)), Ok("Join stamp \"Moon\"".into()));
        assert_eq!(edit(&mut d, 1, &StampEdit::Delete), Ok("Delete stamp \"Star\"".into()));
        assert_eq!(d.stamps.iter().map(|s| s.name.as_str()).collect::<Vec<_>>(), ["Moon"]);
        assert_eq!(edit(&mut d, 3, &StampEdit::Delete), Err("The design has no stamp 3".into()));
        d.graph = Some(serde_json::json!({}));
        let before = d.stamps.clone();
        assert_eq!(edit(&mut d, 0, &StampEdit::Delete), Err(DRIVEN.into()));
        assert_eq!(d.stamps, before, "a refusal changes nothing");
    }
}
